baseURL = "https://dtan13.tech/"
title = "DTan13"
theme = "coder"
languageCode = "en"
defaultContentLanguage = "en"
enableEmoji = false
disableComments = true
disableKinds = ['taxonomyTerm', 'taxonomy', 'term']
paginate = 0
# Enable Twemoji
enableTwemoji = false
# Custom CSS
customCSS = []
# Custom SCSS
customSCSS = []
# Custom JS
customJS = [
    "https://unpkg.com/@codersrank/activity@0.9.10/codersrank-activity.min.js"
]

[params]
author = "Dhananjay Tanpure"
description = "Dhananjay's personal website"
keywords = "blog,developer,personal"
info = []
avatarURL = "/images/avatar.png"
#gravatar = ""
# footerContent = '''echo Hi There > /dev/pts/$(tty | cut -d"/" -f$(echo 1+3 | bc))'''
dateFormat = "January 2, 2006"
hideFooter = true
hideCredits = true
hideCopyright = false
since = 2020
rtl = false
colorScheme = "dark"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 0

[[params.social]]
name = "Email"
icon = "fa fa-envelope"
weight = 1
url = "mailto:dtan13@pm.me"

[[params.social]]
name = "Github"
icon = "fa fa-github"
weight = 2
url = "https://github.com/DTan13/"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-linkedin"
weight = 3
url = "https://www.linkedin.com/in/dtan13/"

[[params.social]]
name = "Stackoverflow"
icon = "fa fa-stack-overflow"
weight = 4
url = "https://stackoverflow.com/users/10990171"

[[params.social]]
name = "ResearchGate"
icon = "fa fa-researchgate"
weight = 5
url = "https://www.researchgate.net/profile/Dhananjay-Tanpure"

[[params.social]]
name = "Gitlab"
icon = "fa fa-gitlab"
weight = 6
url = "https://gitlab.com/DTan13/"

[[params.social]]
name = "Telegram"
icon = "fa fa-telegram"
weight = 7
url = "https://telegram.me/DTan13/"

[[params.social]]
name = "Twitter"
icon = "fa fa-twitter"
weight = 8
url = "https://twitter.com/theDTan13/"

[[menu.main]]
name = "Blog"
weight = 1
url = "https://blog.dtan13.tech"
