baseURL = "http://dtan13.tech"
title = "DTan13"
theme = "coder"
languageCode = "en"
defaultContentLanguage = "en"
enableEmoji = true
disableComments = true
disableKinds = ['taxonomyTerm', 'taxonomy', 'term']
paginate = 0
# Enable Twemoji
enableTwemoji = false
# Custom CSS
customCSS = []
# Custom SCSS
customSCSS = []
# Custom JS
customJS = []

[params]
author = "Dhananjay Tanpure"
description = "Dhananjay's personal website"
keywords = "blog,developer,personal"
info = []
avatarURL = "/images/avatar.png"
#gravatar = ""
# footerContent = '''echo Hi there! > /dev/pts/$(tty | cut -d"/" -f4)'''
dateFormat = "January 2, 2006"
hideFooter = false
hideCredits = true
hideCopyright = false
since = 2021
rtl = false
colorScheme = "dark"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 0

[[params.social]]
name = "Email"
icon = "fa fa-envelope"
weight = 1
url = "mailto:dtan13@pm.me"

[[params.social]]
name = "Github"
icon = "fa fa-github"
weight = 2
url = "https://github.com/DTan13/"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-linkedin"
weight = 3
url = "https://linkedin.com/in/dtan13/"

[[params.social]]
name = "Stackoverflow"
icon = "fa fa-stack-overflow"
weight = 4
url = "https://stackoverflow.com/users/10990171"

[[params.social]]
name = "ResearchGate"
icon = "fa fa-researchgate"
weight = 5
url = "https://www.researchgate.net/profile/Dhananjay-Tanpure"

[[params.social]]
name = "Gitlab"
icon = "fa fa-gitlab"
weight = 6
url = "https://gitlab.com/DTan13/"

[[params.social]]
name = "Telegram"
icon = "fa fa-telegram"
weight = 7
url = "https://telegram.me/DTan13/"

[[params.social]]
name = "KeyBase"
icon = "fa fa-keybase"
weight = 8
url = "https://keybase.io/DTan13/"

[[params.social]]
name = "Reddit"
icon = "fa fa-reddit"
weight = 9
url = "https://reddit.com/u/dtan13/"

[[params.social]]
name = "Twitter"
icon = "fa fa-twitter"
weight = 10
url = "https://twitter.com/DTan13_/"

[[params.social]]
name = "Patreon"
icon = "fa fa-patreon"
weight = 11
url = "https://patreon.com/dtan13"

[[params.social]]
name = "Instagram"
icon = "fa fa-instagram"
weight = 12
url = "https://instagram.com/DTan.13/"

[[params.social]]
name = "RSS"
icon = "fa fa-rss"
weight = 13
url = "https://blog.dtan13.tech/index.xml"
rel = "alternate"
type = "application/rss+xml"

[[menu.main]]
name = "Blog"
weight = 1
url = "https://blog.dtan13.tech"

[[menu.main]]
name = "Projects"
weight = 2
url = "projects/"

[[menu.main]]
name = "About"
weight = 3
url = "about/"
